name: Build and Push Docker images

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: kirbah
  DOCKER_IMAGE: blue-green

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Blue image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: COLOR=blue
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:blue
      
      - name: Build and push Green image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: COLOR=green
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:green
